name: CI & CD

on:
  push:
    branches: [master]
    tags: ["v*"]
  pull_request:
    branches: [master]

jobs:
  # CI
  integration:
    runs-on: ubuntu-latest
    steps:
      - name: clone parent repository
        uses: actions/checkout@v3
        with:
          repository: torrency/torrency
          token: ${{ secrets.CLONE_TOKEN }}
          submodules: true

      - name: Setup Java JDK
        uses: actions/setup-java@v3.6.0
        with:
          java-version: 11
          distribution: zulu

      - name: Restore Build Cache
        uses: actions/cache@v3
        with:
          key: v1-ttorrent-${{ hashFiles('ttorrent-core/pom.xml') }}
          path: ~/.m2/repository

      - name: Unit Test
        run: mvn --no-transfer-progress test
        working-directory: ttorrent-core
